services:
  minecraft:
    # Last updated Sunday, September 6 2026
    image: itzg/minecraft-server:java25-jdk@sha256:f6c674167d6a62402950f8a28e25a46f4d69c223de18fa5b10d49341908f87aa

    networks:
      mc-monitoring:
        aliases:
          - minecraft

    ports:
      - "127.0.0.1:25565:25565/tcp"
      - "127.0.0.1:19132:19132/udp"

    pull_policy: never
    read_only: true
    tty: false
    stdin_open: false

    security_opt:
      - seccomp:unconfined
    cap_drop:
      - ALL
    user: "1000:1000"
    tmpfs:
      - /tmp:exec,mode=1777
      - /run

    cap_add:
      - NET_ADMIN
      - NET_RAW

    deploy:
      resources:
        limits:
          memory: 4608M
          cpus: '2.5'
        reservations:
          memory: 1024M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

    env_file:
      - .system.env
      - .mc.env
    secrets:
      - rcon_password
    volumes:
      - ./data:/data
    restart: unless-stopped

  playit:
    # Last updated Sunday, September 6 2026
    image: ghcr.io/playit-cloud/playit-agent:1.0.10@sha256:ca4766ced6e5bcee19137337808ec8fee5867c0910ac737efbb0bb452c378521

    network_mode: host

    env_file:
      - .playit.env
    volumes:
      - ./playit_data:/etc/playit
    depends_on:
      - minecraft
    restart: unless-stopped

secrets:
  rcon_password:
    file: ./rcon_password.txt

networks:
  mc-monitoring:
    external: true
